---
before_install:
  - "npm update"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - "npm install"
language: node_js
node_js:
  - "8"
script:
  - "npm test"
  - "npm run coveralls"
sudo: false
